CREATE VIEW SARS_COV_2
AS
SELECT ID_REGISTRO, USMER, INSTITUCION, ENTIDAD_FEDERATIVA_UM, GENERO, ENTIDAD_FEDERATIVA_NAC, ENTIDAD_FEDERATIVA_RES, MUNICIPIO_RES, TIPO_ATENCION,
FECHA_INGRESO, FECHA_SINTOMAS, FECHA_DEF, PAC_INTUBADO, PAC_NEUMONIA, EDAD, NACION, PAC_EMBARAZO, PAC_HABLA_LENGUA_INDIG,
PAC_INDIGENA, PAC_DIABETES, PAC_EPOC, PAC_ASMA, PAC_INMUSUPR, PAC_HIPERTENSION, PAC_OTRA_COM, PAC_CARDIOVASCULAR, PAC_OBESIDAD,
PAC_RENAL_CRONICA, PAC_TABAQUISMO , OTRO_CASO, PAC_TOMA_MUESTRA_LAB, LABORATORIO, PAC_TOMA_MUESTRA_ANTIGENO,
ANTIGENO, RESULTADO_FINAL, MIGRANTE, PAIS_NACIONALIDAD, PAIS_ORIGEN, UCI FROM GENERAL
INNER JOIN ORIGEN ON GENERAL.ORIGEN = ORIGEN.ORIGEN
INNER JOIN SECTOR ON GENERAL.SECTOR = SECTOR.SECTOR
INNER JOIN ENTIDADES_UM ON GENERAL.ENTIDAD_UM = ENTIDADES_UM.ENTIDAD_UM
INNER JOIN SEXO ON GENERAL.SEXO = SEXO.SEXO
INNER JOIN ENTIDADES_NAC ON GENERAL.ENTIDAD_NAC = ENTIDADES_NAC.ENTIDAD_NAC
INNER JOIN ENTIDADES_RES ON GENERAL.ENTIDAD_RES = ENTIDADES_RES.ENTIDAD_RES
INNER JOIN TIPO_PACIENTE ON GENERAL.TIPO_PACIENTE = TIPO_PACIENTE.TIPO_PACIENTE
INNER JOIN INTUBADO ON GENERAL.INTUBADO = INTUBADO.INTUBADO
INNER JOIN NEUMONIA ON GENERAL.NEUMONIA = NEUMONIA.NEUMONIA
INNER JOIN NACIONALIDAD ON GENERAL.NACIONALIDAD = NACIONALIDAD.NACIONALIDAD
INNER JOIN EMBARAZO ON GENERAL.EMBARAZO = EMBARAZO.EMBARAZO
INNER JOIN HABLA_LENGUA_INDIG ON GENERAL.HABLA_LENGUA_INDIG = HABLA_LENGUA_INDIG.HABLA_LENGUA_INDIG
INNER JOIN INDIGENA ON GENERAL.INDIGENA = INDIGENA.INDIGENA
INNER JOIN DIABETES ON GENERAL.DIABETES = DIABETES.DIABETES
INNER JOIN EPOC ON GENERAL.EPOC = EPOC.EPOC
INNER JOIN ASMA ON GENERAL.ASMA = ASMA.ASMA
INNER JOIN INMUSUPR ON GENERAL.INMUSUPR = INMUSUPR.INMUSUPR
INNER JOIN HIPERTENSION ON GENERAL.HIPERTENSION = HIPERTENSION.HIPERTENSION
INNER JOIN OTRA_COM ON GENERAL.OTRA_COM = OTRA_COM.OTRA_COM
INNER JOIN CARDIOVASCULAR ON GENERAL.CARDIOVASCULAR = CARDIOVASCULAR.CARDIOVASCULAR
INNER JOIN OBESIDAD ON GENERAL.OBESIDAD = OBESIDAD.OBESIDAD
INNER JOIN RENAL_CRONICA ON GENERAL.RENAL_CRONICA = RENAL_CRONICA.RENAL_CRONICA
INNER JOIN TABAQUISMO ON GENERAL.TABAQUISMO = TABAQUISMO.TABAQUISMO
INNER JOIN TOMA_MUESTRA_LAB ON GENERAL.TOMA_MUESTRA_LAB = TOMA_MUESTRA_LAB.TOMA_MUESTRA_LAB
INNER JOIN RESULTADO_LAB ON GENERAL.RESULTADO_LAB = RESULTADO_LAB.RESULTADO_LAB
INNER JOIN TOMA_MUESTRA_ANTIGENO ON GENERAL.TOMA_MUESTRA_ANTIGENO = TOMA_MUESTRA_ANTIGENO.TOMA_MUESTRA_ANTIGENO
INNER JOIN RESULTADO_ANTIGENO ON GENERAL.RESULTADO_ANTIGENO = RESULTADO_ANTIGENO.RESULTADO_ANTIGENO
INNER JOIN CLASIFICACION_FINAL ON GENERAL.CLASIFICACION_FINAL = CLASIFICACION_FINAL.CLASIFICACION_FINAL